/** 한국어 뜻 표기 교정 (DB의 뜻 → 교정된 뜻) */
export const KO_DISPLAY_OVERRIDE: Record<string, string> = {
  'stair/stairs': 'stair, stairs',
  신: '하나님',
  하루: '날, 하루',
  '남겨 두다': '모아 두다',
  모의하다: '~의 모의 실험을 하다',
  '조수(물때)': '파도(물결)',
  두꺼운: '두꺼운, 걸쭉한, 진한',
  파악하다: '이해하다, 파악하다',
  '(먼지를) 털다': '(먼지를) 털다, 닦다',
  다채로운: '다채로운, 알록달록한',
  훌륭한: '멋진, 훌륭한',
  정원: '정원, 공원',
  생각: '아이디어, 생각',
  뛰다: '뛰다, 뛰어넘다',
  기쁜: '기쁨, 기쁜, 만족스러운',
  '흉내 내다': '흉내내다, 모의로 하다',
  '어떤 ~든': '아무, 어떤 ~든',
  실내의: '실내에서',
  오랫동안: '오래, 오랫동안',
  놀람: '놀람, 쇼크',
  '~을 좋아하다': '~을 더 좋아하다, 선호하다',
  '결정(체)': '크리스탈, 결정(체)',
  논리적으로: '논리적인',
  즉각적인: '즉각적인, 인스턴트',
  기절시키다: '정신을 혼미하게 하다',
  '종교인(설교자)': '성직자, 설교자',
  대통령직의: '대통령의',
  취약한: '위험에 처한',
  위험한: '치명적인',
  '회원 자격': '멤버십, 회원 자격',
  단계: '단계, 위상',
  '(미) 정식 무도회': '(미) 정식 무도회, 갈라 행사',
  '~할 수 있었다/~일 수도 있다(가능성)': '(~할) 수 있을 텐데 / ~할 수 있을까(가정·공손한 가능)',
  종교인: '신앙인, 종교인',
  몸짓: '신호, 제스처, 몸짓',
  '(~을) 활용하다': '이익을 얻다, (~을) 활용하다',
  성악의: '보컬, 노래',
  적당히: '적절하게',
  충분히: '충분한',
  가상의: '온라인, 가상의',
  '졸고 있는': '졸고 있다',
  대관절: '도대체, 대관절',
  뚜렷한: '뚜렷하게',
  '(공기 등을) 넣어 부풀리기': '바람 넣다 / 공기 주입하다',
  '알legally': '~라고 주장된다 / ~라고 알려졌다',
  '(감정이 배제된) 냉정한': '감정 없이',
  추방: '전근, 이주',
  '유사(성)': '유사(성), 유추, 비유',
  삽입: '입력, 삽입',
  대통령직: '대통령직, 대통령직임, 대통령직 수행',
  '(비유적으로) 치열한 संघर्ष의 현장': '(비유적으로) 치열한 투쟁의 현장',
  위독하게: '위독한 상태로',
  광학의: '검안, 안과, 광학',
  '(음악) 성악의': '(음악) 노래의, 보컬의, 성악의',
  '알legedly': '~라고 주장된다 / ~라고 알려졌다',
  allegedly: '~라고 주장된다 / ~라고 알려졌다',
  '지방 사람(지방 출신)': '지방/시골 쪽(지역)에(서)',
  '반어(법)': '조롱, 반어(법)',
}

/** 영어 뜻 음성 제거 (word → 해당 단어의 meaning_en_audio_url 무음 처리, TTS 이상 발음 방지) */
export const MUTE_MEANING_EN_AUDIO_BY_WORD: Set<string> = new Set([])

/**
 * 영어 뜻: 저장된 MP3가 예전 meaning_en(예: drug cocktail)로 생성됐는데
 * 표시는 cocktail 등으로 교정된 경우 — URL 대신 Azure로 화면 문구(englishGlossLineForTts)만 읽기.
 */
export const PREFER_CLIENT_MEANING_EN_TTS_BY_WORD: Set<string> = new Set(['kokteli', '칵테일'])

/** 단어별 한국어 뜻 표기 교정 (word → 교정된 meaning_ko) */
export const KO_DISPLAY_OVERRIDE_BY_WORD: Record<string, string> = {
  nyeupe: '흰색(의)',
  kahawia: '갈색(의)',
  dhahabu: '금; 금색/금빛(의)',
  'kituo cha kuhifadhi': '보관소, 보호소(유기견)',
  hasa: '특히',
  ushirikishwaji: '포용, 포함',
  kiti: '의자',
  kuweka: '(무엇을) 놓다, 세팅하다, 설정하다',
  kipofu: '시각장애인, 맹인',
  kutabiri: '예측하다, 예언하다',
  mtarajiwa: '잠재의, 예비의',
  tupu: '멍한, 텅빈',
  Machi: '3월',
}

/** 영어 뜻 표기 교정 (DB meaning_en → 교정된 표기) */
export const EN_DISPLAY_OVERRIDE: Record<string, string> = {
  about: 'around',
  breach: 'violate',
  comic: 'comedian',
  distinct: 'distinctly',
  medical: 'medical check-up',
  loom: 'approach',
  forge: "blacksmith's workshop",
  allegedly: 'be alleged',
  outing: 'out',
  'beam of light': 'beam',
  'to distance': 'distant',
  clinical: 'without emotion',
  'drug cocktail': 'cocktail',
  critically: 'in critical condition',
  optical: 'optic',
  'a formal': 'formal dance',
  irony: 'mockery, irony',
  exile: 'relocation, transfer',
  'management; the act of running/organizing a business or team': 'management',
  'to exploit': 'make good use',
  'asleep; not aware': 'doze off, be drowsy',
  'provincial; person from the provinces': 'from the provinces',
  outstanding: 'unresolved',
  bridge: 'bridge of the nose',
  contract: 'be infected, catch',
  venture: 'dare',
  float: 'buoy',
  buck: 'male rabbit',
  male: 'male rabbit',
  pack: 'package',
  'to be late': 'late',
  cut: 'crop',
  cute: 'be cute',
  'to settle': 'calm down',
  aspire: 'operate',
  'to mind; to look after': 'look after',
  possible: 'be possible',
  aware: 'be aware',
  offer: 'special offer',
  master: 'captain',
  passing: 'brief',
  report: 'pin',
  tight: 'be tight',
  'to lie': 'be located',
  throw: 'bin',
  delegate: 'me',
  relieved: 'be relieved',
  regard: 'regarding',
  resolve: 'decide',
  'to ring': 'call',
  'to present': 'introduce',
  alarm: 'shock, fright, alarm',
  'instant; immediate': 'immediate, instant',
  immediately: 'immediate, instant',
  enough: 'be enough',
  fond: 'prefer',
  homeless: 'stray (animal)',
  establishment: 'institution',
  'to desert': 'abandon',
  'rational; logical': 'rational',
  bake: 'harden, thicken',
  leap: 'jump at/on, pounce on',
  'to staff': 'hire',
  'to be controversial': 'controversial',
  deadly: 'dangerous',
  discourage: 'be discouraged',
  get: 'persuade',
  practitioner: 'religious person, believer',
  preacher: 'religious person, believer',
  letters: 'symbol, sign, character',
  removal: 'move',
  dynamic: 'interaction',
  thinking: 'idea, thinking',
  wit: 'wisdom, good sense',
  exploit: 'benefit (from), gain',
  'to submit': 'surrender',
  random: 'randomly',
  gaming: 'gambling',
  sufficiently: 'enough',
  virtual: 'online',
  rationally: 'rational',
  involved: 'complicated',
  building: 'construction',
  vulnerable: 'in danger, at risk',
  communicate: 'convey',
  martial: 'military',
  means: 'method',
  'to troop': 'accompany, go together',
  'theatrical; dramatic': 'theatrical',
  'to be proud': 'proud',
  power: 'authority',
  visual: 'visual aid',
  action: 'activity',
  gala: 'formal',
  remainder: 'remaining, balance',
  character: 'symbol, sign, character',
  seize: 'understand, grasp',
  'to dust': 'dust, wipe',
  kind: 'form',
  keep: 'save',
  appealing: 'interesting',
  'largely; mainly': 'especially',
  cycle: 'repeat',
  naturally: 'usually',
  lie: 'be, be located',
  'stair/stairs': 'stair, stairs',
  'split / crack': 'split, crack',
  'privacy / private life': 'privacy, private life',
  'conception / concept': 'conception, concept',
  'composition / work': 'composition, work',
  'combination / code': 'combination, code',
  'meantime / meanwhile': 'meanwhile',
  'in danger / at risk': 'in danger, at risk',
  'yet / still': 'yet, still',
  'creep/crawl': 'creep, crawl',
  'remaining/balance': 'remaining, balance',
  'nominate/appoint': 'nominate, appoint',
  'to nominate/appoint': 'to nominate, appoint',
  'engaged/busy': 'engaged, busy',
  'make/force': 'make, force',
  'to make/force': 'to make, force',
  'collapse / fall down': 'collapse, fall down',
  'adjust / adapt': 'adjust, adapt',
  'to adjust / adapt': 'to adjust, adapt',
  'elbow, accidentally hit/push with the elbow': 'elbow, accidentally hit or push with the elbow',
  'to elbow, accidentally hit/push with the elbow':
    'to elbow, accidentally hit or push with the elbow',
  'private/secret': 'private, secret',
  'the latest news/updates': 'the latest news',
  'reverse/turn something over': 'reverse',
  'to reverse/turn something over': 'reverse',
  'crawl / creep': 'crawl',
  'creep / crawl': 'crawl',
  'bear/give birth': 'bear, give birth',
  'to bear/give birth': 'to bear, give birth',
  'conceive/become pregnant': 'conceive, become pregnant',
  'to conceive/become pregnant': 'to conceive, become pregnant',
  'drift/wander aimlessly': 'wander aimlessly',
  'to drift/wander aimlessly': 'to wander aimlessly',
  'immune': 'be immune',
  'to buy': 'afford',
  'deployment; arranging/placing people or things for a task': 'deployment; arranging, placing people or things for a task',
  'to complicated': 'be complicated',
  'to unavoidable': 'be unavoidable',
  'to pin': 'pin',
  'transit transfer; changing lines/vehicles': 'transit transfer; changing lines, vehicles',
  'association; an organization/group': 'association; an organization, group',
  'to grand': 'be grand',
  'to flexible': 'be flexible',
  'to congested': 'be congested',
  'to viable': 'be viable',
  'to steady': 'be steady',
  'to broadcast': 'be broadcast',
  'to inappropriate': 'be inappropriate',
  'to desirable': 'be desirable',
  'to to follow or stick to rules or standards': 'comply with',
  'adhere; to follow or stick to rules or standards': 'comply with',
  'to able to detect small changes': 'be sensitive',
  'logical; based on reason': 'be logical',
  'to to cover a surface with paint': 'paint',
  'to pass': 'be eager',
  'to eager': 'be eager',
  'relevant; closely connected to what is being discussed': 'be relevant',
  'to different from what is normal': 'be different from what is normal',
  'unusual; different from what is normal': 'be different from what is normal',
  worthwhile: 'be worth',
  'to watch': 'be depressing',
  'to holy': 'be sacred',
  'to courteous': 'be courteous',
  'to very beautiful': 'be gorgeous',
  'gorgeous; very beautiful': 'be gorgeous',
  'to inflict': 'hurt',
  outfit: 'set',
  'number of members': 'membership',
  'to unpleasant': 'be unpleasant',
  'to strict': 'be strict',
  'to harsh and unforgiving': 'be harsh',
  'to unfair': 'be unfair',
  'to sustain; to maintain': 'be sustained',
  'to sustain': 'be sustained',
  'dynamic; full of energy and activity': 'be dynamic',
  'to distinctive': 'distinctive',
  'to be distinctive': 'distinctive',
  spectacular: 'be spectacular',
  /** DB/생성본이 단수 sport일 때 학습용으로 복수 sports(운동·스포츠)로 통일 */
  sport: 'sports',
  'prominent; noticeable': 'distinctive',
  'to to restrain oneself': 'restrain oneself',
  'stark; harsh and unforgiving': 'be harsh',
  'polite; courteous': 'be polite; be courteous',
  'paint; to cover a surface with paint': 'paint',
  'to very unpleasant': 'be very unpleasant',
  'to humorous': 'be humorous',
  'to brazen': 'be brazen',
  'to competent': 'be competent',
  'to humble': 'be humble',
  'to mature': 'be mature',
  'to serious': 'be serious',
  'to mild': 'be mild',
  'to be': 'warn',
  'to perfect': 'be complete',
  'film-maker; a person who directs/makes films': 'film-maker; a person who directs, makes films',
  'to especially for a job': 'interview',
  'to subtle': 'be subtle',
  'to predictable': 'be predictable',
  'to keep': 'be only right',
  'to suspicious': 'be suspicious',
  'to valid': 'be valid',
  'alternative; another option/solution': 'alternative; another option, solution',
  'seeker; a device/program/person that searches for a target': 'explorer',
  'coal/charcoal': 'coal, charcoal',
  'much/many': 'much, many',
  little: 'a little',
  folks: 'parents',
  gradually: 'slowly',
  development: 'news',
  old: 'an elderly man',
  ever: 'on earth',
  'on earth': 'on earth',
  'to exercise': 'used to',
  'to very deep in meaning': 'have a deep meaning',
  'to make': 'empower',
  'to feasible': 'be feasible',
  'future / later': 'future, later',
  'to very clear and obvious': 'be clear and obvious',
  'to urgent and in great need': 'be urgent',
  'to work': 'operate',
  'to say': 'intend',
  'to silent': 'switch',
  'to be hit with a fist': 'punch',
  'to my': 'adapt',
  'to the': 'pin',
  'to license / permit': 'license',
  'to dishonest': 'be dishonest',
  'to careless': 'be careless',
  'to miserable': 'be miserable',
  'excess': 'excessive',
  'to task/assign': 'task, assign',
  'to participate': 'encourage',
  'to distant': 'distant',
  'to support': 'rally',
  'to grade/mark': 'grade, mark',
  'enthusiastic; passionate': 'be enthusiastic',
  'to enthusiastic; passionate': 'be enthusiastic',
  'to proud': 'proud',
  'to absurd': 'be absurd',
  'to hazard a guess; to अनुमान roughly': 'hazard a guess; guess roughly',
  'electoral; relating to elections/voters': 'electoral; relating to elections, voters',
  'mixed; blended/conflicting': 'mixed; blended, conflicting',
  'resistance; opposition by refusing to accept/control': 'resistance; opposition by refusing to accept, control',
  'deteriorate': 'get worse',
  'to deteriorate': 'get worse',
  'to graphic': 'vivid',
  'graphic': 'vivid',
  'eligible; qualified/entitled': 'eligible; qualified, entitled',
  'extensively; broadly/thoroughly': 'extensively; broadly, thoroughly',
}

/** 단어별 영어 뜻 표기 교정 (word → 교정된 meaning_en) */
export const EN_DISPLAY_OVERRIDE_BY_WORD: Record<string, string> = {
  '원래': 'originally',
  '진정시키다': 'calm',
  '의식': 'a ritual',
  '그것': 'it',
  '분야': 'a field',
  '디스크': 'a disc',
  '소풍': 'an outing',
  '북쪽의': 'northern',
  '기록하다': 'record',
  '가로막다': 'block',
  '프로토콜': 'protocol; an official set of rules',
  '그 밖에': 'else; in addition',
  '정돈된': 'straight; tidy',
  '참다': 'tolerate; put up with',
  '부드러운': 'gentle; soft',
  '이상': 'beyond, more than',
  '존경하다': 'respect',
  '자금': 'funding, funds',
  '조종하다': 'steer',
  '운영': 'governance; management',
  '수 있다': 'could; be able to',
  '휘젓다': 'whisk',
  '흉내 내다': 'simulate',
  '찢다': 'rip',
  '화장실': 'toilet, restroom',
  '기한': 'due date, deadline',
  '정렬': 'alignment, arrangement',
  '것 같다': 'seem, appear',
  '영화관': 'cinema, movie theater',
  '할당량': 'quota; assigned amount',
  '부탁하다': 'appeal, ask',
  '정돈되다': 'be organized',
  '구성하다': 'comprise, make up',
  '늘리다': 'stretch, build up',
  safu: 'array; row, column',
  '처리하다': 'handle, deal with',
  '허가하다': 'license',
  '도대체': 'on earth',
  '열정적이다': 'be enthusiastic',
  '선거의': 'electoral',
  '뒤섞인': 'mixed',
  '저항': 'resistance',
  '자격이 있는': 'eligible; qualified',
  '광범위하게': 'extensively; broadly',
  '대안': 'alternative; another option',
  ngazi: 'stair, stairs',
  inaripotiwa: 'beam',
  hasa: 'especially',
  '방과 후 남기': 'after school',
  사소하다: 'trivial',
  광범위하다: 'extensive',
  감상: 'appreciate',
  유효하다: 'be valid',
  결심하다: 'decide',
  영화감독: 'film-maker',
  엄격한: 'strict',
  엄격하다: 'be strict',
  인플레이션: 'inflation',
  협회: 'association; an organization, group',
  환승: 'transit transfer; changing lines, vehicles',
  친절하다: 'be kind',
  신성하다: 'be sacred',
  공손하다: 'be polite',
  자연스럽게: 'naturally',
  배치: 'deployment; arranging',
  작품: 'composition, work',
  균열: 'split, crack',
  사생활: 'privacy, private life',
  개념: 'conception, concept',
  관례적이다: 'conventionally',
  유머러스하다: 'be humorous',
  임상적인: 'clinical',
  짐작하다: 'guess',
  혼잡하다: 'be crowded; be congested',
  수확량: 'yield',
  칵테일: 'cocktail',
  높다: 'be high',
  '실행 가능하다': 'be viable',
  꾸준하다: 'be steady',
  둘째로: 'secondly',
  위임하다: 'delegate',
  두드러지다: 'distinctive',
  가하다: 'inflict',
  우세: 'dominate',
  매력적이다: 'attractive',
  과도하다: 'excessive',
  자치: 'right to autonomy',
  단련하다: 'strengthen, build',
  입히다: 'hurt',
  programu: 'programming',
  편성: 'programming schedule',
  '프로그램 편성': 'programming schedule',
  mpangilio: 'programming schedule',
  zipu: 'zipper',
}

/** 단어별 스와힐리어 뜻 표기 교정 (word → 교정된 meaning_sw) */
export const SW_DISPLAY_OVERRIDE_BY_WORD: Record<string, string> = {
  kiti: '의자',
  사소하다: 'dogo',
  자치: 'haki ya kujitawala',
  배출: 'moshi wa gari/magari',
  단련하다: 'kuimarisha',
  두드러지다: 'dhahiri; inayoonekana',
  관례적이다: 'kwa kawaida',
  임상적인: 'ya kliniki',
}

/** 스와힐리어 뜻 표기 교정 (DB의 뜻 → 교정된 뜻) */
export const SW_DISPLAY_OVERRIDE: Record<string, string> = {
  'stair/stairs': 'stair, stairs',
  'kubaki shule baada ya masomo kama adhabu (detention)': 'baada ya masomo',
  'kuwa ndogo; isiyo muhimu sana': 'dogo',
  'bahati tu; kwa nasibu': 'bahati tu',
  'kufurahia sanaa; kutazama na kuthamini': 'kufurahia',
  'kuwa halali; inayotumika': 'kuwa halali',
  'kuwa na nguvu zaidi; ubabe (kushinda)': 'kushinda',
  'ziada kupita kiasi': '-a kupindukia',
}

/**
 * 한국어 뜻에 오버라이드 적용
 * rawMeaning은 DB에서 가져온 원본(쉼표 split 전 또는 후 모두 가능)
 */
export function applyKoOverride(word: string | null, rawMeaning: string | null): string | null {
  if (!rawMeaning) return rawMeaning
  if (word && KO_DISPLAY_OVERRIDE_BY_WORD[word]) return KO_DISPLAY_OVERRIDE_BY_WORD[word]
  return KO_DISPLAY_OVERRIDE[rawMeaning] ?? rawMeaning
}

/** 영어 뜻에 오버라이드 적용 */
export function applyEnOverride(rawMeaning: string | null, word?: string | null): string | null {
  if (!rawMeaning) return rawMeaning
  if (word && EN_DISPLAY_OVERRIDE_BY_WORD[word]) return EN_DISPLAY_OVERRIDE_BY_WORD[word]
  return EN_DISPLAY_OVERRIDE[rawMeaning] ?? rawMeaning
}

/** 스와힐리어 뜻에 오버라이드 적용 */
export function applySwOverride(word: string | null, rawMeaning: string | null): string | null {
  if (!rawMeaning) return rawMeaning
  if (word && SW_DISPLAY_OVERRIDE_BY_WORD[word]) return SW_DISPLAY_OVERRIDE_BY_WORD[word]
  return SW_DISPLAY_OVERRIDE[rawMeaning] ?? rawMeaning
}

/** 예문 텍스트/발음 표시 교정 (DB 원본 → 화면 표시) */
export const EXAMPLE_DISPLAY_OVERRIDE: Record<string, { text: string; pron?: string }> = {
  /** 수 관형사: 스물하나 명 → 스물한 명 */
  '참가자가 스물하나 명이에요.': {
    text: '참가자가 스물한 명이에요.',
    pron: 'chamgajaga seumulhan myeongieyo.',
  },
  '회의가 스물셋 분에 끝났어요.': {
    text: '스물세 명의 학생이 운동장에 모여서 체육대회를 준비했어요.',
    pron: 'seumulse myeong-ui haksaeng-i undongjang-e moyeoseo cheyukdaehoe-reul junbihasseoyo.',
  },
  '하루는 스물넷 시간이죠.': {
    text: '스물네 개의 연필을 사서 친구들에게 나누어 주었어요.',
    pron: 'seumulne gae-ui yeonpireul saseo chingudeul-ege nanueo jueosseoyo.',
  },
  '학생이 32명 있어요.': {
    text: '삼십이 명의 손님이 잔치에 와서 함께 식사를 했어요.',
    pron: 'samsib-i myeong-ui sonnim-i janchi-e waseo hamkke siksareul haesseoyo.',
  },
  '표가 35장 남았어요.': {
    text: '삼십오 개의 사과를 사서 이웃들과 함께 나누어 먹었어요.',
    pron: 'samsib-o gae-ui sagwareul saseo iutdeulgwa hamkke nanueo meogeosseoyo.',
  },
  /** 표기는 값이, 발음·TTS는 연음 형태(기름갑씨) */
  '요즘 기름값이 급등했어요.': {
    text: '요즘 기름값이 급등했어요.',
    pron: 'yojeun gireumgabssi geupdeunghaesseoyo.',
  },
  '저는 열셋 살이에요.': { text: '저는 열세 살이에요.', pron: 'jeoneun yeolse sarieyo.' },
  '이 길은 끝없는 것 같아.': { text: '이 길은 끝없는 것 같아.', pron: 'I gireun kkeudeomneun geot gata.' },
  '사람들은 후보를 지지하려고 광장에 집회했어요.': { text: '사람들은 후보를 지지하려고 광장에서 집회했어요.', pron: 'saramdeureun huboreul jijiharyeogo gwangjang-eseo jiphoehae-sseoyo.' },
  '예비의 신입사원이 내일 와요.': { text: '예비 신입사원이 내일 와요.', pron: 'yebi sinipsawoni naeil wayo.' },
  '그는 지적이고 차분한 사람이에요.': { text: '그는 지적이고 차분한 사람이에요.', pron: 'geuneun jijeokigo chabunhan saramieyo.' },
  '내일은 기념의 행사가 있어요.': { text: '내일은 기념 행사가 있어요.', pron: 'naeireun ginyeom haengsaga isseoyo.' },
  '숙제를 안 해서 방과 후 남기를 했어요.': { text: '숙제를 안 해서 방과 후 남아서 벌을 받게 되었어요.', pron: 'Sukjereul an haeseo banggwa hu namaseo beoreul batge doeeosseoyo.' },
  '이 잔은 크리스털로 만들었어요.': { text: '이 잔은 크리스탈로 만들었어요.', pron: 'I janeun keuriseutallo mandeureosseoyo.' },
  '좋은 교육자는 학생을 잘 들어요.': {
    text: '좋은 교육자는 학생 말을 잘 들어요.',
    pron: 'joeun gyoyukjaneun haksaeng maleul jal deureoyo.',
  },
  '이 보고서는 통계의 자료를 바탕으로 썼어요.': {
    text: '이 보고서는 통계 자료를 바탕으로 썼어요.',
    pron: 'i bogoseoneun tonggye jaryoreul batang-euro sseosseoyo.',
  },
  '우리 회사는 태양광의 전기를 써요.': {
    text: '우리 회사는 태양광 전기를 써요.',
    pron: 'uri hoesaneun taeyanggwang jeongi-reul sseoyo.',
  },
  '의사 말로는 급성의 위염이래요.': {
    text: '의사 말로는 급성 위염이래요.',
    pron: 'uisa mallo-neun geupseong wieom-iraeyo.',
  },
  '사과를 일 개 샀어요.': {
    text: '저는 지하철 일 번 출구에서 기다릴게요.',
    pron: 'jeoneun jihacheol il beon chulgueseo gidarilgeyo',
  },
  '책을 이 권 빌렸어요.': {
    text: '우리 집은 이 층에 있어요.',
    pron: 'urijibeun i cheunge isseoyo',
  },
  '친구가 삼 명 왔어요.': {
    text: '저는 삼 일 동안 제주도에 있었어요.',
    pron: 'jeoneun sam il dong-an jejudo-e isseosseoyo',
  },
  '의자가 사 개 있어요.': {
    text: '사 월에는 꽃이 많이 펴요.',
    pron: 'sa wole-neun kkochi mani pyeoyo',
  },
  '학생이 육 명 있어요.': {
    text: '그는 육 개월 동안 한국어를 공부했어요.',
    pron: 'geuneun yuk gaewol dong-an hangugeo-reul gongbuhaesseoyo',
  },
  '칠 시에 만나요.': {
    text: '우리 아파트는 칠 층에 있어요.',
    pron: 'uri apateuneun chil cheunge isseoyo',
  },
  '문제가 십 개예요.': {
    text: '회의는 십 분 후에 시작해요.',
    pron: 'hoeuineun sip bun hue sijakhaeyo',
  },
  '저는 열한 시에 일어나요.': {
    text: '제 생일은 십일 월 십일 일이에요.',
    pron: 'je saengireun sibir wol sibir irieyo',
  },
  '우리는 열두 명이에요.': {
    text: '우리 사무실은 십이 층에 있어요.',
    pron: 'uri samusireun sibi cheunge isseoyo',
  },
  '버스가 14번이에요.': {
    text: '버스가 십사번이에요.',
    pron: 'beoseuga sipsabeonieyo',
  },
  '사과를 15개 샀어요.': {
    text: '회의는 십오 분 후에 시작해요.',
    pron: 'hoeuineun sibo bun hue sijakhaeyo',
  },
  '교실에 의자가 16개 있어요.': {
    text: '우리 집은 십육 층에 있어요.',
    pron: 'uri jibeun simnyuk cheunge isseoyo',
  },
  '저는 17살이에요.': {
    text: '저는 십칠 번 좌석에 앉았어요.',
    pron: 'jeoneun sipchil beon jwaseoge anajasseoyo',
  },
  '책을 19권 읽었어요.': {
    text: '우리 집은 십구 층에 있어요.',
    pron: 'uri jibeun sipgu cheunge isseoyo',
  },
  '저는 스무 살이에요.': {
    text: '회의는 이십 분 후에 시작해요.',
    pron: 'hoeuineun isip bun hue sijakhaeyo',
  },
  '저는 스무두 살이에요.': {
    text: '우리 사무실은 이십이 층에 있어요.',
    pron: 'uri samusireun isibi cheunge isseoyo',
  },
  '저는 스물둘 살이에요.': {
    text: '스물두 살이 된 동생은 올해 처음으로 혼자 여행을 갔어요.',
    pron: 'seumuldu sal-i doen dongsaeng-eun olhae cheoeum-euro honja yeohaeng-eul gasseoyo.',
  },
  '책을 22권 읽었어요.': {
    text: '우리 사무실은 이십이 층에 있어요.',
    pron: 'uri samusireun isibi cheunge isseoyo',
  },
  '저는 22살이에요.': {
    text: '우리 사무실은 이십이 층에 있어요.',
    pron: 'uri samusireun isibi cheunge isseoyo',
  },
  '참가자는 모두 22명이에요.': {
    text: '우리 사무실은 이십이 층에 있어요.',
    pron: 'uri samusireun isibi cheunge isseoyo',
  },
  '저는 23살이에요.': {
    text: '제 번호표는 이십삼 번이에요.',
    pron: 'je beonhoponeun isipsam beonieyo',
  },
  '하루는 24시간이에요.': {
    text: '오늘은 이십사 페이지까지 읽었어요.',
    pron: 'oneureun isipsa peijikkaji ilgeosseoyo',
  },
  '저는 스물여섯 살이에요.': {
    text: '이 엘리베이터는 이십육 층까지 가요.',
    pron: 'i ellibeiteoneun isibyuk cheungkkaji gayo',
  },
  '버스는 29번을 타세요.': {
    text: '버스는 이십구번을 타세요.',
    pron: 'beoseuneun isipgubeoneul taseyo',
  },
  '연필이 열하나 자루 있어요.': {
    text: '연필이 열한 자루 있어요.',
    pron: 'yeonpiri yeolhan jaru isseoyo',
  },
  '사과를 스물 개 샀어요.': {
    text: '사과를 스무 개 샀어요.',
    pron: 'sagwareul seumu gae sasseoyo',
  },
  '8월에는 날씨가 정말 더워요.': {
    text: '8월에는 날씨가 아주 더워요.',
    pron: 'parworeneun nalssiga aju deowoyo',
  },
  '오늘 하늘이 정말 아름다워요.': {
    text: '아름다운 외모뿐만 아니라 마음도 따뜻한 사람이에요.',
    pron: 'areumdaun oemoppunman anira maeumdo ttatteuthan saramieyo.',
  },
  '아기 고양이가 정말 귀여워요.': {
    text: '아기는 통통한 볼이 정말 귀여워요.',
    pron: 'agineun tongtonghan bori jeongmal gwiyeowoyo.',
  },
  '이 가게는 분위기가 이국적이에요.': {
    text: '그 모델은 이국적인 얼굴선이 아주 매력적이에요.',
    pron: 'geu modereun igukjeogin eolgulseoni aju maeryeokjeogieyo.',
  },
  '그 말투는 좀 촌스러워요.': {
    text: '화장이 진해서 오히려 촌스러워 보일 수 있어요.',
    pron: 'hwajangi jinhaeseo ohiryeo chonseureowo boil su isseoyo.',
  },
}

/** 예문 한국어 번역 표기 교정 (DB 원본 → 교정된 번역) */
export const EXAMPLE_TRANSLATION_KO_OVERRIDE: Record<string, string> = {
  '많은 사람들이 매일 신께 기도해요.': '많은 사람들이 매일 하나님께 기도해요.',
  '이 반지에는 아주 반짝이는 크리스털이 있어요.': '이 반지에는 아주 반짝이는 크리스탈이 있어요.',
  '오늘 달의 위상은 보름달이야.': '오늘 달의 위상(달의 모양 단계)은 보름달이야.',
  '우리는 내일 시장에 갈 거예요. 과일 사는 것도 포함해서요.': '내일 시장에 가는데, 과일도 사는 걸 포함해요.',
  '그의/그녀의 옷차림은 정말 연극적이었어.': '그의/그녀의 옷차림은 정말 연극적(무대 의상 같은)이었어.',
  '오늘 시장에 사람이 바글바글하고 활동이 많았어요.': '오늘 시장에 사람이 많고 활기가 넘쳤어요.',
  '저는 연주곡보다 보컬 음악을 더 좋아해요.': '저는 기악곡보다 보컬(노래) 음악을 더 좋아해요.',
  '모두가 이해할 수 있게 충분히 설명해 주세요.': '모든 사람이 이해할 수 있도록 적절하게(제대로) 설명해 주세요.',
  '망명 생활 때문에 그는 가족과 떨어져 살아야 했어.': '전근(이동 발령) 때문에 가족과 멀리 떨어져 살아야 했어요.',
  '그 호텔에는 방이 스물넷 개 있어요.': '그 호텔에는 방이 스물네 개 있어요.',
  '나는 책을 스물셋 권 샀어.': '나는 책을 스물세 권 샀어.',
  '나는 마흔하나 살이에요.': '나는 마흔한 살이에요.',
  '우리는 달걀 마흔셋 개를 샀어요.': '우리는 달걀 마흔세 개를 샀어요.',
  '버스에 좌석이 마흔넷 개 있어요.': '버스에 좌석이 마흔네 개 있어요.',
  '여행은 마흔다섯 분 걸릴 거예요.': '여행은 사십오 분 걸릴 거예요.',
  '의사 말로는 급성의 위염이래요.': '의사 말로는 급성 위염이래요.',
}

/** 예문 영어 번역 표기 교정 (DB 원본 → 교정된 번역) */
export const EXAMPLE_TRANSLATION_EN_OVERRIDE: Record<string, string> = {
  'That movie is very appealing.': 'That movie is very interesting.',
  'Exile forced him to live far from his family.': 'The transfer forced him/her to live far from his/her family.',
}

/** 단어별 예문 번역 교정 (word → { sw?, ko?, en?, koPron? }) */
export const EXAMPLE_TRANSLATION_OVERRIDE_BY_WORD: Record<string, { sw?: string; ko?: string; en?: string; koPron?: string }> = {
  '아름다운': {
    sw: 'Si sura nzuri tu, bali pia ni mtu mwenye moyo wa joto.',
    en: 'Not only beautiful in appearance, but also a warm-hearted person.',
  },
  '귀엽다': {
    sw: 'Mtoto ana mashavu ya mviringo ambayo ni ya kupendeza sana.',
    en: 'The baby has chubby cheeks that are really cute.',
  },
  '이국적인': {
    sw: 'Modeli huyo ana sura ya kigeni ambayo inavutia sana.',
    en: 'That model has exotic facial features that are very attractive.',
  },
  '이국적이다': {
    sw: 'Modeli huyo ana sura ya kigeni ambayo inavutia sana.',
    en: 'That model has exotic facial features that are very attractive.',
  },
  '촌스럽다': {
    sw: 'Mapambo mengi ya uso yanaweza kuonekana ya kishamba badala yake.',
    en: 'Heavy makeup can actually make you look unsophisticated.',
  },
  자치: {
    sw: 'Jiji hili lina haki ya kujitawala.',
    en: 'This city has the right to autonomy.',
  },
  Machi: {
    ko: '우리는 3월에 시작해요.',
    en: 'We start in March.',
    koPron: 'urineun samwore sijakhaeyo',
  },
  '3월': {
    sw: 'Tunaanza mwezi wa Machi.',
    en: 'We start in March.',
  },
  스물둘: {
    sw: 'Ndugu yangu mdogo aliyeifikia umri wa miaka ishirini na mbili, alienda safari peke yake kwa mara ya kwanza mwaka huu.',
    en: 'My younger sibling, who turned twenty-two, went on a trip alone for the first time this year.',
  },
  스물셋: {
    sw: 'Wanafunzi ishirini na watatu walikusanyika uwanjani wa michezo kuandaa mashindano ya michezo.',
    en: 'Twenty-three students gathered on the playground to prepare for the sports day.',
  },
  스물넷: {
    sw: 'Nilinunua penseli ishirini na nne nikazigawa kwa marafiki zangu.',
    en: 'I bought twenty-four pencils and shared them with my friends.',
  },
  삼십이: {
    sw: 'Wageni thelathini na wawili walifika kwenye sherehe na kula pamoja.',
    en: 'Thirty-two guests came to the party and had a meal together.',
  },
  삼십오: {
    sw: 'Nilinunua tufaha thelathini na tano nikagawa na majirani wangu na kula pamoja.',
    en: 'I bought thirty-five apples and shared them with my neighbors, and we ate them together.',
  },
  '8월': {
    sw: 'Hali ya hewa huwa ya joto sana mwezi wa Agosti.',
    en: 'The weather is very hot in August.',
  },
  일: {
    sw: 'Nitangoja kwenye mlango wa namba moja wa treni ya chini ya ardhi.',
    en: "I'll wait at subway exit number one.",
  },
  moja: {
    sw: 'Nitangoja kwenye mlango wa namba moja wa treni ya chini ya ardhi.',
    en: "I'll wait at subway exit number one.",
  },
  이: {
    sw: 'Nyumba yetu iko kwenye ghorofa ya pili.',
    en: 'Our house is on the second floor.',
  },
  mbili: {
    sw: 'Nyumba yetu iko kwenye ghorofa ya pili.',
    en: 'Our house is on the second floor.',
  },
  삼: {
    sw: 'Nilikuwa Jeju kwa siku tatu.',
    en: 'I was in Jeju for three days.',
  },
  tatu: {
    sw: 'Nilikuwa Jeju kwa siku tatu.',
    en: 'I was in Jeju for three days.',
  },
  사: {
    sw: 'Mwezi wa nne kuna maua mengi yanachanua.',
    en: 'In April, many flowers bloom.',
  },
  nne: {
    sw: 'Mwezi wa nne kuna maua mengi yanachanua.',
    en: 'In April, many flowers bloom.',
  },
  육: {
    sw: 'Alisoma Kikorea kwa miezi sita.',
    en: 'He studied Korean for six months.',
  },
  sita: {
    sw: 'Alisoma Kikorea kwa miezi sita.',
    en: 'He studied Korean for six months.',
  },
  칠: {
    sw: 'Apartmenti yetu iko kwenye ghorofa ya saba.',
    en: 'Our apartment is on the seventh floor.',
  },
  saba: {
    sw: 'Apartmenti yetu iko kwenye ghorofa ya saba.',
    en: 'Our apartment is on the seventh floor.',
  },
  십: {
    sw: 'Mkutano unaanza baada ya dakika kumi.',
    en: 'The meeting starts in ten minutes.',
  },
  kumi: {
    sw: 'Mkutano unaanza baada ya dakika kumi.',
    en: 'The meeting starts in ten minutes.',
  },
  십일: {
    sw: 'Siku yangu ya kuzaliwa ni tarehe kumi na moja mwezi wa kumi na moja.',
    en: 'My birthday is November 11th.',
  },
  'kumi na moja': {
    sw: 'Siku yangu ya kuzaliwa ni tarehe kumi na moja mwezi wa kumi na moja.',
    en: 'My birthday is November 11th.',
  },
  십이: {
    sw: 'Ofisi yetu iko kwenye ghorofa ya kumi na mbili.',
    en: 'Our office is on the twelfth floor.',
  },
  'kumi na mbili': {
    sw: 'Ofisi yetu iko kwenye ghorofa ya kumi na mbili.',
    en: 'Our office is on the twelfth floor.',
  },
  십사: {
    sw: 'Basi ni namba kumi na nne.',
    en: 'The bus is number 14.',
  },
  'kumi na nne': {
    sw: 'Basi ni namba kumi na nne.',
    en: 'The bus is number 14.',
  },
  십오: {
    sw: 'Mkutano unaanza baada ya dakika kumi na tano.',
    en: 'The meeting starts in fifteen minutes.',
  },
  'kumi na tano': {
    sw: 'Mkutano unaanza baada ya dakika kumi na tano.',
    en: 'The meeting starts in fifteen minutes.',
  },
  십육: {
    sw: 'Nyumba yetu iko kwenye ghorofa ya kumi na sita.',
    en: 'Our house is on the sixteenth floor.',
  },
  'kumi na sita': {
    sw: 'Nyumba yetu iko kwenye ghorofa ya kumi na sita.',
    en: 'Our house is on the sixteenth floor.',
  },
  십칠: {
    sw: 'Nilikaa kiti cha namba kumi na saba.',
    en: 'I sat in seat number seventeen.',
  },
  'kumi na saba': {
    sw: 'Nilikaa kiti cha namba kumi na saba.',
    en: 'I sat in seat number seventeen.',
  },
  십구: {
    sw: 'Nyumba yetu iko kwenye ghorofa ya kumi na tisa.',
    en: 'Our house is on the nineteenth floor.',
  },
  'kumi na tisa': {
    sw: 'Nyumba yetu iko kwenye ghorofa ya kumi na tisa.',
    en: 'Our house is on the nineteenth floor.',
  },
  이십: {
    sw: 'Mkutano unaanza baada ya dakika ishirini.',
    en: 'The meeting starts in twenty minutes.',
  },
  ishirini: {
    sw: 'Mkutano unaanza baada ya dakika ishirini.',
    en: 'The meeting starts in twenty minutes.',
  },
  이십이: {
    sw: 'Ofisi yetu iko kwenye ghorofa ya ishirini na mbili.',
    en: 'Our office is on the twenty-second floor.',
  },
  'ishirini na mbili': {
    sw: 'Ofisi yetu iko kwenye ghorofa ya ishirini na mbili.',
    en: 'Our office is on the twenty-second floor.',
  },
  이십삼: {
    sw: 'Tikiti yangu ya namba ni namba ishirini na tatu.',
    en: 'My number ticket is number twenty-three.',
  },
  'ishirini na tatu': {
    sw: 'Tikiti yangu ya namba ni namba ishirini na tatu.',
    en: 'My number ticket is number twenty-three.',
  },
  이십사: {
    sw: 'Leo nilisoma hadi kurasa ishirini na nne.',
    en: 'I read up to page twenty-four today.',
  },
  'ishirini na nne': {
    sw: 'Leo nilisoma hadi kurasa ishirini na nne.',
    en: 'I read up to page twenty-four today.',
  },
  이십육: {
    sw: 'Lifi hii inaenda hadi ghorofa ya ishirini na sita.',
    en: 'This elevator goes up to the twenty-sixth floor.',
  },
  'ishirini na sita': {
    sw: 'Lifi hii inaenda hadi ghorofa ya ishirini na sita.',
    en: 'This elevator goes up to the twenty-sixth floor.',
  },
  스물여섯: {
    sw: 'Lifi hii inaenda hadi ghorofa ya ishirini na sita.',
    en: 'This elevator goes up to the twenty-sixth floor.',
  },
  이십구: {
    sw: 'Panda basi namba ishirini na tisa.',
    en: 'Take bus number twenty-nine.',
  },
  'ishirini na tisa': {
    sw: 'Panda basi namba ishirini na tisa.',
    en: 'Take bus number twenty-nine.',
  },
}

/** 단어 텍스트/발음 표시 교정 (DB 원본 word → 교정된 word, pron) */
export const WORD_DISPLAY_OVERRIDE: Record<string, { word: string; pron: string }> = {
  신: { word: '하나님', pron: 'hananim' },
  우세: { word: '우세하다', pron: 'usehada' },
  매력적이다: { word: '매력적인', pron: 'maeryeokjeogin' },
  끝없는: { word: '끝없는', pron: 'kkeudeomneun' },
  끝없다: { word: '끝없는', pron: 'kkeudeomneun' },
  다혈질이다: { word: '다혈질인', pron: 'dahyeoljirin' },
  충성스럽다: { word: '충성스러운', pron: 'chungseongseureon' },
  끊임없다: { word: '끊임없는', pron: 'kkeunim-eomneun' },
  충격적이다: { word: '충격적인', pron: 'chunggyeokjeogin' },
  이국적이다: { word: '이국적인', pron: 'igukjeogin' },
  합리적이다: { word: '합리적인', pron: 'hamnijeogin' },
  사소하다: { word: '사소한', pron: 'sasohan' },
  부정적이다: { word: '부정적인', pron: 'bujeongjeogin' },
  방어적이다: { word: '방어적인', pron: 'bangeojeogin' },
  현대적이다: { word: '현대적인', pron: 'hyeondaejeogin' },
  실용적이다: { word: '실용적인', pron: 'sillyongjeogin' },
  역사적이다: { word: '역사적인', pron: 'yeoksajeogin' },
  광범위하다: { word: '광범위한', pron: 'gwangbeomwihan' },
  노골적이다: { word: '노골적인', pron: 'nogoljeogin' },
  인상적이다: { word: '인상적인', pron: 'insangjeogin' },
  치명적이다: { word: '치명적인', pron: 'chimyeongjeogin' },
  생생하다: { word: '생생한', pron: 'saengsaenghan' },
  앞서: { word: '앞서 있는', pron: 'apseo inneun' },
  차갑다: { word: '차가운', pron: 'chagaun' },
  구식이다: { word: '구식의', pron: 'gusigui' },
  과도하다: { word: '과도한', pron: 'gwadohan' },
  과도: { word: '과도한', pron: 'gwadohan' },
  예비: { word: '예비(의)', pron: 'yebiui' },
  예비의: { word: '예비(의)', pron: 'yebiui' },
  기념의: { word: '기념(의)', pron: 'ginyeomui' },
  '방과 후 남기': { word: '방과 후', pron: 'banggwa hu' },
  실제의: { word: '실제(의)', pron: 'siljeoui' },
  감상: { word: '감상하다', pron: 'gamsanghada' },
  상징적이다: { word: '상징적인', pron: 'sangjingjeogin' },
  대략적이다: { word: '대략적인', pron: 'daeryakjeogin' },
  자치: { word: '자치권', pron: 'jachigwon' },
  크리스털: { word: '크리스탈', pron: 'keuriseutal' },
  배출: { word: '배출가스', pron: 'baechulgaseu' },
  지적이다: { word: '지적이다', pron: 'jijjeogida' },
  현실적이다: { word: '현실적인', pron: 'hyeonsiljeogin' },
  인공적이다: { word: '인공적인', pron: 'ingongjeogin' },
  어이없다: { word: '어이없는', pron: 'eoieomneun' },
  '-(으)ㄹ 거예요': { word: '거예요', pron: 'geoyeyo' },
  결정적이다: { word: '결정적인', pron: 'gyeoljeongjeogin' },
  간접적이다: { word: '간접적인', pron: 'ganjeopjeogin' },
  낙관적이다: { word: '낙관적인', pron: 'nakgwanjeogin' },
  엄청나다: { word: '엄청난', pron: 'eomcheongnan' },
  구체적이다: { word: '구체적인', pron: 'guchejeogin' },
  행정적이다: { word: '행정적인', pron: 'haengjeongjeogin' },
  혁신적이다: { word: '혁신적인', pron: 'hyeoksinjeogin' },
  이념적이다: { word: '이념적인', pron: 'inyeomjeogin' },
  민족적이다: { word: '민족적인', pron: 'minjokjeogin' },
  독점적이다: { word: '독점적인', pron: 'dokjeomjeogin' },
  통계의: { word: '통계(의)', pron: 'tonggyeui' },
  태양광의: { word: '태양광(의)', pron: 'taeyanggwang-ui' },
  범례: { word: '지도 범례', pron: 'jido beomnye' },
  입히다: { word: '상처를 입히다', pron: 'sangcheoreul iphida' },
  끈질기다: { word: '끈질긴', pron: 'kkeunjilgin' },
  두드러지다: { word: '두드러진', pron: 'dudeureojin' },
  연극적이다: { word: '연극적인', pron: 'yeongeukjeogin' },
  잦다: { word: '잦은', pron: 'jajeun' },
  glovu: { word: 'glovu za ndondi', pron: 'GLO-vu za NDO-ndi' },
  맹인: { word: '시각장애인, 맹인', pron: 'siggakjangaein, maengin' },
  관례적이다: { word: '관례적으로', pron: 'gwanryejeogeuro' },
  안다: { word: '안다', pron: 'antta' },
  용돈: { word: '용돈', pron: 'yongtton' },
}

/** 예문별 영어 뜻 표기 교정 (예문이 동일한데 뜻이 다른 경우) */
export const EN_DISPLAY_OVERRIDE_BY_EXAMPLE: Record<string, string> = {
  'The programming schedule has changed this week.': 'programming schedule',
}
